name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_launcher_icons: ^0.14.4
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.6.1
  
flutter:
  uses-material-design: true
  assets:
  - .env
flutter_launcher_icons:
  image_path: "assets/icon/icone_app.png"
  android: true