site_name: Lumina

repo_url: https://github.com/unb-mds/2025-2-Lumina
repo_name: 'Lumina'

nav:
  - Início: index.md
  - Arquitetura:
      - Arquitetura: arquitetura/diagramas/arquitetura.md
      - Diagramas: arquitetura/diagramas/diagramas.md
  - Levantamento de Requisitos:
      - Requisitos: requisitos/Requisitos.md
      - Story Map: requisitos/StoryMap.md
  - Estudos:
      - Arquitetura de sistemas: estudos/Arquitetura_de_Sistemas.md
      - Boas práticas de documentação: estudos/Boas_Praticas_de_Documentacao.md
      - Definição de produto: estudos/Definição_de_Produto.md
      - Arquitetura de agentes de IA: estudos/Arquitetura_de_Agentes_de_IA.md
      - Como hospedar um app na Play Store: estudos/Como_Hospedar_um_App_na_PlayStore.md
      - APIs e WebCrawlers: estudos/APIs_e_WebCrawlers.md
      - Docker: estudos/Docker.md
      - Figma: estudos/Figma.md
      - Sites estáticos: estudos/Sites_Estaticos.md
      - RAG e aplicações: estudos/RAG_e_Aplicações.md
      - Flutter e Dart: estudos/Flutter_e_Dart.md
      - Análise de Métricas Ágeis no GitHub: estudos/Ferramentas_de_Desempenho.md
      - Git e GitHub: estudos/Git_e_GitHub.md
      - GitHub Insights: estudos/GitHub_Insights.md
      - Métricas de OpenSource: estudos/Metricas_de_OpenSouce.md
      - Persistência de dados em Flutter: estudos/Persistencia_de_dados(flutter).md
      - Requisitos: estudos/Requisitos.md
      - Testes: estudos/Testes.md
      - Teste unitário em Flutter: estudos/Teste_Unitário_em_flutter.md
      - Tecnologias Backend: estudos/Tecnologias_Backend.md
      - Tecnologias Frontend: estudos/Tecnologias_Frontend.md
  - Planejamento:
       - Cronograma do Projeto: planejamentos/cronograma.md
       - Backlog de Produto: planejamentos/backlog.md
       - Sprints:
          - Sprint 00: planejamentos/sprints/sprint_00.md
          - Sprint 01: planejamentos/sprints/sprint_01.md
          - Sprint 02: planejamentos/sprints/sprint_02.md
          - Sprint 03: planejamentos/sprints/sprint_03.md
          - Sprint 04: planejamentos/sprints/sprint_04.md
          - Sprint 05: planejamentos/sprints/sprint_05.md
          - Sprint 06: planejamentos/sprints/sprint_06.md
          - Sprint 07: planejamentos/sprints/sprint_07.md
          - Sprint 08: planejamentos/sprints/sprint_08.md
          - Sprint 09: planejamentos/sprints/sprint_09.md
          - Sprint 10: planejamentos/sprints/sprint_10.md
          - Sprint 11: planejamentos/sprints/sprint_11.md
          - Sprint 12: planejamentos/sprints/sprint_12.md
       - Atas:
          - Ata Sprint 00: planejamentos/atas/ata_sprint00.md
          - Ata Sprint 01: planejamentos/atas/ata_sprint01.md
          - Ata Sprint 02: planejamentos/atas/ata_sprint02.md
          - Ata Sprint 03: planejamentos/atas/ata_sprint03.md
          - Ata Sprint 04: planejamentos/atas/ata_sprint04.md
          - Ata Sprint 05: planejamentos/atas/ata_sprint05.md
          - Ata Sprint 06: planejamentos/atas/ata_sprint06.md
          - Ata Sprint 07: planejamentos/atas/ata_sprint07.md
          - Ata Sprint 08: planejamentos/atas/ata_sprint08.md
          - Ata Sprint 09: planejamentos/atas/ata_sprint09.md
          - Ata Sprint 10: planejamentos/atas/ata_sprint10.md
          - Ata Sprint 11: planejamentos/atas/ata_sprint11.md
          - Ata Sprint 12: planejamentos/atas/ata_sprint12.md

site_url: https://mydomain.org/mysite

theme:
    name: material
    font: Roboto Mono
    palette: 

      # Palette toggle for automatic mode
     - media: "(prefers-color-scheme)"
       toggle:
         icon: material/brightness-auto
         name: Switch to light mode
        

     # Palette toggle for light mode
     - media: "(prefers-color-scheme: light)"
       scheme: default
       toggle:
         icon: material/weather-sunny
         name: Switch to dark mode
       primary: custom

     # Palette toggle for dark mode
     - media: "(prefers-color-scheme: dark)"
       scheme: slate
       toggle:
         icon: material/weather-night
         name: Switch to system preference
       primary: custom

    features:
      - navigation.footer

    logo: assets/logo.png
    favicon: assets/logo.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.blocks.caption